# Puerto del microservicio
server.port=8081
spring.application.name=ms-socios

# Conexion a MySQL de XAMPP (sin contrasena por defecto)
spring.datasource.url=jdbc:mysql://localhost:3306/db_socios?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Santiago&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate crea/actualiza las tablas automaticamente al arrancar
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# URLs de los otros microservicios para comunicarse
ms.socios.url=http://localhost:8081
ms.planes.url=http://localhost:8082
ms.pagos.url=http://localhost:8083
ms.clases.url=http://localhost:8084
ms.instructores.url=http://localhost:8085
ms.equipamiento.url=http://localhost:8086
ms.asistencia.url=http://localhost:8087
ms.notificaciones.url=http://localhost:8088

spring.jpa.defer-datasource-initialization=true

# Forzar ejecucion de data.sql siempre
spring.sql.init.mode=always
